title: scratch3-copy-costumes-from-one-sprite-to-another
hero_image: images/banner.png
description: scratch3-copy-costumes-from-one-sprite-to-another description
version: 4
listed: false
copyedit: false
last_tested: "2021-03-12"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
